1.单词向量空间模型通过单词的向量表示文本的语义内容。以单词-文本矩阵$X$为输入，其中每一行对应一个单词，每一列对应一个文本，每一个元素表示单词在文本中的频数或权值（如TF-IDF）
$$X = \left[ \begin{array} { c c c c } { x _ { 11 } } & { x _ { 12 } } & { \cdots } & { x _ { 1 n } } \\ { x _ { 21 } } & { x _ { 22 } } & { \cdots } & { x _ { 2 n } } \\ { \vdots } & { \vdots } & { } & { \vdots } \\ { x _ { m 1 } } & { x _ { m 2 } } & { \cdots } & { x _ { m n } } \end{array} \right]$$
单词向量空间模型认为，这个矩阵的每一列向量是单词向量，表示一个文本，两个单词向量的内积或标准化内积表示文本之间的语义相似度。

2.话题向量空间模型通过话题的向量表示文本的语义内容。假设有话题文本矩阵$$Y = \left[ \begin{array} { c c c c } { y _ { 11 } } & { y _ { 12 } } & { \cdots } & { y _ { 1 n } } \\ { y _ { 21 } } & { y _ { 22 } } & { \cdots } & { y _ { 2 n } } \\ { \vdots } & { \vdots } & { } & { \vdots } \\ { y _ { k 1 } } & { y _ { k 2 } } & { \cdots } & { y _ { k n } } \end{array} \right]$$
其中每一行对应一个话题，每一列对应一个文本每一个元素表示话题在文本中的权值。话题向量空间模型认为，这个矩阵的每一列向量是话题向量，表示一个文本，两个话题向量的内积或标准化内积表示文本之间的语义相似度。假设有单词话题矩阵$T$
$$T = \left[ \begin{array} { c c c c } { t _ { 11 } } & { t _ { 12 } } & { \cdots } & { t _ { 1 k } } \\ { t _ { 21 } } & { t _ { 22 } } & { \cdots } & { t _ { 2 k } } \\ { \vdots } & { \vdots } & { } & { \vdots } \\ { t _ { m 1 } } & { t _ { m 2 } } & { \cdots } & { t _ { m k } } \end{array} \right]$$ 
其中每一行对应一个单词，每一列对应一个话题，每一个元素表示单词在话题中的权值。

给定一个单词文本矩阵$X$
$$X = \left[ \begin{array} { c c c c } { x _ { 11 } } & { x _ { 12 } } & { \cdots } & { x _ { 1 n } } \\ { x _ { 21 } } & { x _ { 22 } } & { \cdots } & { x _ { 2 n } } \\ { \vdots } & { \vdots } & { } & { \vdots } \\ { x _ { m 1 } } & { x _ { m 2 } } & { \cdots } & { x _ { m n } } \end{array} \right]$$

潜在语义分析的目标是，找到合适的单词-话题矩阵$T$与话题文本矩阵$Y$，将单词文本矩阵$X$近似的表示为$T$与$Y$的乘积形式。
$$X \approx T Y$$

等价地，潜在语义分析将文本在单词向量空间的表示X通过线性变换$T$转换为话题向量空间中的表示$Y$。

潜在语义分析的关键是对单词-文本矩阵进行以上的矩阵因子分解（话题分析）

3.潜在语义分析的算法是奇异值分解。通过对单词文本矩阵进行截断奇异值分解，得到
$$X \approx U _ { k } \Sigma _ { k } V _ { k } ^ { T } = U _ { k } ( \Sigma _ { k } V _ { k } ^ { T } )$$

矩阵$U_k$表示话题空间，矩阵$( \Sigma _ { k } V _ { k } ^ { T } )$是文本在话题空间的表示。

4.非负矩阵分解也可以用于话题分析。非负矩阵分解将非负的单词文本矩阵近似分解成两个非负矩阵$W$和$H$的乘积，得到
$$X \approx W H$$

矩阵$W$表示话题空间，矩阵$H$是文本在话题空间的表示。

非负矩阵分解可以表为以下的最优化问题：
$$\left. \begin{array} { l } { \operatorname { min } _ { W , H } \| X - W H \| ^ { 2 } } \\ { \text { s.t. } W , H \geq 0 } \end{array} \right.$$
非负矩阵分解的算法是迭代算法。乘法更新规则的迭代算法，交替地对$W$和$H$进行更新。本质是梯度下降法，通过定义特殊的步长和非负的初始值，保证迭代过程及结果的矩阵$W$和$H$均为非负。


## 单词向量空间  
word vector space model

给定一个文本，用一个向量表示该文本的”语义“， 向量的**每一维对应一个单词**，其数值为该单词在该文本中出现的频数或权值；基本假设是文本中所有单词的出现情况表示了文本的语义内容，文本集合中的每个文本都表示为一个向量，存在于一个向量空间；向量空间的度量，如内积或标准化**内积**表示文本之间的**相似度**。

给定一个含有$n$个文本的集合$D=({d_{1}, d_{2},...,d_{n}})$，以及在所有文本中出现的$m$个单词的集合$W=({w_{1},w_{2},...,w_{m}})$. 将单词在文本的出现的数据用一个单词-文本矩阵（word-document matrix）表示，记作$X$:

$
X = \begin{bmatrix}
x_{11} &  x_{12}&  x_{1n}& \\ 
x_{21}&  x_{22}&  x_{2n}& \\ 
\vdots &  \vdots &  \vdots & \\ 
x_{m1}&  x_{m2}&  x_{mn}& 
\end{bmatrix}
$

这是一个$m*n$矩阵，元素$x_{ij}$表示单词$w_{i}$在文本$d_{j}$中出现的频数或权值。由于单词的种类很多，而每个文本中出现单词的种类通常较少，所有单词-文本矩阵是一个稀疏矩阵。



权值通常用单词**频率-逆文本率**（term frequency-inverse document frequency, TF-IDF）表示：

$TF-IDF(t, d ) = TF(t, d) * IDF(t)$,  

其中，$TF(t,d)$为单词$t$在文本$d$中出现的概率，$IDF(t)$是逆文本率，用来衡量单词$t$对表示语义所起的重要性， 

$IDF(t) = log(\frac{len(D)}{len(t \in D) + 1})$.

单词向量空间模型的优点是**模型简单，计算效率高**。因为单词向量通常是稀疏的，单词向量空间模型也有一定的局限性，体现在内积相似度未必能够准确表达两个文本的语义相似度上。因为自然语言的单词具有一词多义性（polysemy）及多词一义性（synonymy）。

In [1]:
import numpy as np
from sklearn.decomposition import TruncatedSVD

In [2]:
X = [[2, 0, 0, 0], [0, 2, 0, 0], [0, 0, 1, 0], [0, 0, 2, 3], [0, 0, 0, 1], [1, 2, 2, 1]]
X = np.asarray(X);X

array([[2, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 2, 3],
       [0, 0, 0, 1],
       [1, 2, 2, 1]])

In [3]:
# 奇异值分解
U,sigma,VT=np.linalg.svd(X)

In [4]:
U

array([[-7.84368672e-02,  2.84423033e-01,  8.94427191e-01,
         2.15138396e-01, -2.68931121e-02, -2.56794523e-01],
       [-1.56873734e-01,  5.68846066e-01, -4.47213595e-01,
         4.30276793e-01, -5.37862243e-02, -5.13589047e-01],
       [-1.42622354e-01, -1.37930417e-02, -6.93889390e-17,
        -6.53519444e-01,  4.77828945e-01, -5.69263078e-01],
       [-7.28804669e-01, -5.53499910e-01,  5.55111512e-17,
         1.56161345e-01, -2.92700697e-01, -2.28957508e-01],
       [-1.47853320e-01, -1.75304609e-01, -6.93889390e-18,
         4.87733411e-01,  8.24315866e-01,  1.73283476e-01],
       [-6.29190197e-01,  5.08166890e-01,  1.11022302e-16,
        -2.81459486e-01,  5.37862243e-02,  5.13589047e-01]])

In [5]:
sigma

array([4.47696617, 2.7519661 , 2.        , 1.17620428])

In [6]:
VT

array([[-1.75579600e-01, -3.51159201e-01, -6.38515454e-01,
        -6.61934313e-01],
       [ 3.91361272e-01,  7.82722545e-01, -3.79579831e-02,
        -4.82432341e-01],
       [ 8.94427191e-01, -4.47213595e-01, -5.55111512e-17,
        -8.32667268e-17],
       [ 1.26523351e-01,  2.53046702e-01, -7.68672366e-01,
         5.73674125e-01]])

In [7]:
svd = TruncatedSVD(n_components=3, n_iter=7, random_state=42)
svd.fit(X)  

TruncatedSVD(algorithm='randomized', n_components=3, n_iter=7, random_state=42,
             tol=0.0)

In [8]:
print(svd.explained_variance_ratio_)

[0.39945801 0.34585056 0.18861789]


In [9]:
print(svd.explained_variance_ratio_.sum())

0.933926460028448


In [10]:
print(svd.singular_values_)

[4.47696617 2.7519661  2.        ]


#### 非负矩阵分解

In [11]:
def inverse_transform(W, H):
    # 重构
    return W.dot(H)

def loss(X, X_):
    #计算重构误差
    return ((X - X_) * (X - X_)).sum()

In [12]:
# 算法 17.1

class MyNMF:
    def fit(self, X, k, t):
        m, n = X.shape
        
        W = np.random.rand(m, k)
        W = W/W.sum(axis=0)
        
        H = np.random.rand(k, n)
        
        i = 1
        while i < t:
            
            W = W * X.dot(H.T) / W.dot(H).dot(H.T)
            
            H = H * (W.T).dot(X) / (W.T).dot(W).dot(H)
            
            i += 1
            
        return W, H

In [13]:
model = MyNMF()
W, H = model.fit(X, 3, 200)

In [14]:
W

array([[0.00000000e+00, 0.00000000e+00, 1.28595080e+00],
       [1.28345362e+00, 0.00000000e+00, 0.00000000e+00],
       [1.05790587e-01, 2.67463988e-01, 4.49034869e-02],
       [4.42746168e-09, 1.68311835e+00, 3.97986442e-10],
       [0.00000000e+00, 3.73906428e-01, 0.00000000e+00],
       [1.43275413e+00, 7.52576889e-01, 6.79401001e-01]])

In [15]:
H

array([[2.05124504e-06, 1.46377751e+00, 3.71958802e-01, 4.73580536e-25],
       [3.74460106e-08, 1.19697283e-08, 1.28408868e+00, 1.71047314e+00],
       [1.53560867e+00, 1.55308346e-06, 1.73756527e-01, 1.48990252e-25]])

In [16]:
X_ = inverse_transform(W, H);X_

array([[1.97471720e+00, 1.99718892e-06, 2.23442344e-01, 1.91594134e-25],
       [2.63267787e-06, 1.87869054e+00, 4.77391871e-01, 6.07818654e-25],
       [6.89544109e-02, 1.54853954e-01, 3.90599494e-01, 4.57489968e-01],
       [6.36372282e-08, 2.66272889e-08, 2.16127323e+00, 2.87892874e+00],
       [1.40013040e-08, 4.47555835e-09, 4.80129012e-01, 6.39556902e-01],
       [1.04329704e+00, 2.09723433e+00, 1.61735133e+00, 1.28726256e+00]])

In [17]:
loss(X, X_)

1.5439645173226346

### 使用 sklearn 计算

In [18]:
from sklearn.decomposition import NMF
model = NMF(n_components=3, init='random', max_iter=200, random_state=0)
W = model.fit_transform(X)
H = model.components_

In [19]:
W

array([[0.        , 0.53849498, 0.        ],
       [0.        , 1.07698996, 0.        ],
       [0.69891361, 0.        , 0.        ],
       [1.39782972, 0.        , 1.97173859],
       [0.        , 0.        , 0.65783848],
       [1.39783002, 1.34623756, 0.65573258]])

In [20]:
H

array([[0.00000000e+00, 0.00000000e+00, 1.43078959e+00, 1.71761682e-03],
       [7.42810976e-01, 1.48562195e+00, 0.00000000e+00, 3.30264644e-04],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.52030365e+00]])

In [21]:
X__ = inverse_transform(W, H);X__

array([[3.99999983e-01, 7.99999966e-01, 0.00000000e+00, 1.77845853e-04],
       [7.99999966e-01, 1.59999993e+00, 0.00000000e+00, 3.55691707e-04],
       [0.00000000e+00, 0.00000000e+00, 9.99998311e-01, 1.20046577e-03],
       [0.00000000e+00, 0.00000000e+00, 2.00000021e+00, 3.00004230e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00011424e+00],
       [1.00000003e+00, 2.00000007e+00, 2.00000064e+00, 9.99758185e-01]])

In [22]:
loss(X, X__)

4.0000016725824565